"""phase1 repositories and snapshots

Revision ID: e9af6c0912af
Revises: 
Create Date: 2026-10-01 02:23:30.370943

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision: str = 'e9af6c0912af'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('ingestion_status', sa.String(length=32), nullable=False),
    sa.Column('index_version', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('eligible_file_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_commit_sha'), ['commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_repository_id'), ['repository_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_repository_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_commit_sha'))

    op.drop_table('snapshots')
    op.drop_table('repositories')
    # ### end Alembic commands ###
